# Generated by Django 6.0 on 2025-12-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmuebles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_ultimo_mensaje', models.DateTimeField(blank=True, null=True)),
                ('fecha_disponibilidad_confirmada', models.DateTimeField(blank=True, null=True)),
                ('fecha_desactivacion', models.DateTimeField(blank=True, null=True)),
                ('intetnos_contacto', models.IntegerField(default=0)),
                ('portales', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
