# Generated by Django 6.0 on 2025-12-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialActualizacionesPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('codigo_inmueble', models.CharField(max_length=100)),
                ('tipo_servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_inmueble', models.CharField(blank=True, max_length=150, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=120, null=True)),
                ('conjunto', models.CharField(blank=True, max_length=120, null=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialRespuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('codigo_inmueble', models.CharField(max_length=100)),
                ('tipo_servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_inmueble', models.CharField(blank=True, max_length=150, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=120, null=True)),
                ('conjunto', models.CharField(blank=True, max_length=120, null=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('codigos_externos', models.JSONField(blank=True, null=True)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('razon_desactivacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
