# Generated by Django 6.0 on 2025-12-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialIntervenciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('codigo_inmueble', models.CharField(max_length=100)),
                ('tipo_servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_inmueble', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_intervencion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
