# Generated by Django 6.0 on 2026-01-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automations', '0002_historialintervenciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobiliaToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mobilia_token',
            },
        ),
    ]
