# Generated by Django 6.0 on 2026-01-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automations', '0003_mobiliatoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialintervenciones',
            name='captador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
