# Generated by Django 6.0 on 2026-06-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automations', '0004_historialintervenciones_captador'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('nivel', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], db_index=True, default='INFO', max_length=20)),
                ('evento', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('codigo_inmueble', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('mensaje', models.TextField()),
                ('detalle', models.JSONField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('origen', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Registro de log',
                'verbose_name_plural': 'Registros de log',
                'db_table': 'registro_log',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
