# Generated by Django 6.0 on 2026-06-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automations', '0005_registrolog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioPlantillaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation_id', models.CharField(db_index=True, max_length=100)),
                ('codigo_inmueble', models.CharField(blank=True, max_length=100, null=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('template_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log de envío de plantilla',
                'verbose_name_plural': 'Logs de envío de plantilla',
                'db_table': 'envio_plantilla_log',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
