"""
Django settings for ACRECER_actualizacion_inventario_API project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(nombre, por_defecto=False):
    """Lee una variable de entorno 'boolean-like' ('1', 'true', 'si'...)."""
    valor = os.getenv(nombre)
    if valor is None:
        return por_defecto
    return valor.strip().lower() in ('1', 'true', 'yes', 'si', 'sí')


def _env_lista(nombre, por_defecto=()):
    """Lee una variable separada por comas y devuelve la lista sin vacíos."""
    crudo = os.getenv(nombre)
    if crudo is None:
        return list(por_defecto)
    return [item.strip() for item in crudo.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Por defecto False: si la variable falta, se asume producción. Es más seguro
# fallar cerrado que arrancar con tracebacks públicos por un .env incompleto.
DEBUG = _env_bool('DEBUG', False)

# SECURITY WARNING: keep the secret key used in production secret!
# Sin default productivo: en producción la clave es obligatoria y el arranque
# falla si no está. Solo con DEBUG se permite una clave de desarrollo.
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            "SECRET_KEY es obligatoria cuando DEBUG=False. Defínela en el "
            "entorno (.env) antes de arrancar."
        )
    SECRET_KEY = 'django-insecure-solo-para-desarrollo-local-no-usar-en-produccion'

# Lista separada por comas. En producción hay que declararla explícitamente;
# antes el default '*' aceptaba cualquier Host header.
ALLOWED_HOSTS = _env_lista(
    'ALLOWED_HOSTS',
    por_defecto=('localhost', '127.0.0.1', '[::1]') if DEBUG else (),
)
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        "ALLOWED_HOSTS es obligatorio cuando DEBUG=False. Declara los dominios "
        "servidos, p. ej. ALLOWED_HOSTS=\"midominio.com,api.midominio.com\"."
    )

# Detrás del proxy/balanceador que termina TLS, para que Django reconozca HTTPS.
if _env_bool('USE_X_FORWARDED_PROTO', not DEBUG):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookies solo por HTTPS en producción (protege la sesión del admin). Si el
# despliegue sirve por HTTP plano, ponlas en "False" en el entorno o no se podrá
# iniciar sesión en el admin.
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', not DEBUG)

# Redirección a HTTPS: por defecto DESACTIVADA incluso en producción. Activarla
# sin que el proxy informe el esquema correcto provoca un bucle de redirecciones,
# así que es una decisión explícita de despliegue.
SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', False)

# HSTS: desactivado por defecto. Es difícil de revertir (los navegadores recuerdan
# la cabecera), así que se activa a conciencia una vez el dominio sirve solo TLS.
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', False)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'Inmuebles',
    'Automations'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ACRECER_actualizacion_inventario_API.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ACRECER_actualizacion_inventario_API.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}



# API de envío de plantillas de WhatsApp (antes era el nodo Lambda en n8n).
# Sin defaults: las URLs y tokens de producción se declaran en el entorno, no
# en el repositorio. Si falta la URL, `enviar_plantilla` falla de forma explícita.
WHATSAPP_API_URL = os.getenv('WHATSAPP_API_URL', '')
WHATSAPP_API_TOKEN = os.getenv('WHATSAPP_API_TOKEN', '')
WHATSAPP_DEFAULT_TEMPLATE_ID_ARR = os.getenv('WHATSAPP_DEFAULT_TEMPLATE_ID_ARR', '')

# Webhook de n8n que registra el contacto en PostgreSQL tras enviar la plantilla.
# Vacío ('') desactiva la notificación.
N8N_GUARDAR_PG_WEBHOOK = os.getenv('N8N_GUARDAR_PG_WEBHOOK', '')

# Destinatarios de las notificaciones de negocio (desactivaciones, cambios de
# valor, intervenciones e informe). Lista separada por comas en el entorno.
NOTIFICACION_DESTINATARIOS = _env_lista('NOTIFICACION_DESTINATARIOS')

# Servidor SMTP para las notificaciones (Gmail por defecto).
EMAIL_SMTP_HOST = os.getenv('EMAIL_SMTP_HOST', 'smtp.gmail.com')
EMAIL_SMTP_PORT = int(os.getenv('EMAIL_SMTP_PORT', '587'))

# Segundos que se cachea el listado de inmuebles activos de Mobilia. Cada
# consulta por código descarga el inventario completo, así que un TTL corto
# evita repetir la descarga varias veces dentro de la misma operación.
MOBILIA_CACHE_TTL = int(os.getenv('MOBILIA_CACHE_TTL', '120'))

# Ventana por defecto (días) del informe de historial. 0 = sin límite.
INFORME_DIAS = int(os.getenv('INFORME_DIAS', '30'))

# Token compartido que autoriza la consulta del historial (endpoints
# /api/automations/historial/...). Sin default: si falta, esos endpoints
# responden 403 en lugar de quedar abiertos.
API_INFORMES_TOKEN = os.getenv('API_INFORMES_TOKEN', '')


# Cache / memoria temporal (conversación viva, TTL 24h)
# Usa Redis si REDIS_URL está definido (recomendado en producción, compartido
# entre todos los workers de Gunicorn). En local cae a memoria del proceso.
REDIS_URL = os.getenv('REDIS_URL')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'conversacion-viva',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

# El negocio opera en Colombia: `timezone.localtime()` (nombre del informe, horas
# mostradas) y el cron del contenedor deben coincidir con la hora local.
# Se sigue almacenando en UTC en la base de datos porque USE_TZ está activo.
TIME_ZONE = os.getenv('TIME_ZONE', 'America/Bogota')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Carpeta donde se generan los informes xlsx.
MEDIA_DIR = BASE_DIR / 'Media'


# Logging
# https://docs.djangoproject.com/en/6.0/topics/logging/
#
# Persiste en PostgreSQL (tabla registro_log) solo eventos de negocio y errores:
#   - logger 'automations'   -> INFO+  (intervenciones, desactivaciones, precios, informes...)
#   - logger 'django.request' -> ERROR (excepciones no controladas en las vistas)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'db': {
            'class': 'Automations.logging_handlers.PostgresLogHandler',
            'level': 'INFO',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'automations': {
            'handlers': ['console', 'db'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'db'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
